title: 文章列表
email: wiranchang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  这是一个基于Jekyll的demo部署。
baseurl: "/jekyll-demo" # the subpath of your site, e.g. /blog
url: "https://iwiran.github.io" # the base hostname & protocol for your site

